### ISSUE TITLE
gce-host does not work with google-api-client v0.12.0

### ISSUE THREAD

**Issue by sonots** [sonots/gce-host#5]
```
undefined method `list_aggregated_instances' for #<Google::Apis::ComputeV1::ComputeService:0x0000000234eb10>
```
